Repository callbellchat/callbell-public-docs, pull requests merged in 2024-01, with the labels that each got.

#24 enh: add messages-history endpoint
  README.md
  docs/api/reference/contacts_api/get_contact_messages.md
  docs/api/reference/object_types/message.md
  docs/api/release_notes.md
  i18n/es/docusaurus-plugin-content-docs/current/api/reference/contacts_api/get_contact_messages.md
  i18n/es/docusaurus-plugin-content-docs/current/api/release_notes.md
  i18n/fr/docusaurus-plugin-content-docs/current/api/reference/contacts_api/get_contact_messages.md
  i18n/fr/docusaurus-plugin-content-docs/current/api/release_notes.md
  i18n/it/docusaurus-plugin-content-docs/current/api/reference/contacts_api/get_contact_messages.md
  i18n/it/docusaurus-plugin-content-docs/current/api/release_notes.md
  i18n/pt/docusaurus-plugin-content-docs/current/api/reference/contacts_api/get_contact_messages.md
  i18n/pt/docusaurus-plugin-content-docs/current/api/release_notes.md
  src/snippets/curl/contacts_api/_get_contact_messages.mdx
  src/snippets/go/contacts_api/_get_contact_messages.mdx
  src/snippets/node/contacts_api/_get_contact_messages.mdx
  src/snippets/php/contacts_api/_get_contact_messages.mdx
  src/snippets/python/contacts_api/_get_contact_messages.mdx
  src/snippets/ruby/contacts_api/_get_contact_messages.mdx
Labels: documentation, enhancement

#26 enh: add open / close conversation endpoint docs & examples
  docs/api/reference/contacts_api/patch_contacts.md
  docs/api/reference/contacts_api/post_contact_conversation_close.md
  docs/api/reference/contacts_api/post_contact_conversation_open.md
  docs/api/reference/object_types/contact.md
  docs/api/release_notes.md
  i18n/es/docusaurus-plugin-content-docs/current/api/reference/contacts_api/post_contact_conversation_close.md
  i18n/es/docusaurus-plugin-content-docs/current/api/reference/contacts_api/post_contact_conversation_open.md
  i18n/es/docusaurus-plugin-content-docs/current/api/reference/object_types/contact.md
  i18n/es/docusaurus-plugin-content-docs/current/api/release_notes.md
  i18n/fr/docusaurus-plugin-content-docs/current/api/reference/contacts_api/post_contact_conversation_close.md
  i18n/fr/docusaurus-plugin-content-docs/current/api/reference/contacts_api/post_contact_conversation_open.md
  i18n/fr/docusaurus-plugin-content-docs/current/api/reference/object_types/contact.md
  i18n/fr/docusaurus-plugin-content-docs/current/api/release_notes.md
  i18n/it/docusaurus-plugin-content-docs/current/api/reference/contacts_api/post_contact_conversation_close.md
  i18n/it/docusaurus-plugin-content-docs/current/api/reference/contacts_api/post_contact_conversation_open.md
  i18n/it/docusaurus-plugin-content-docs/current/api/reference/object_types/contact.md
  i18n/it/docusaurus-plugin-content-docs/current/api/release_notes.md
  i18n/pt/docusaurus-plugin-content-docs/current/api/reference/contacts_api/post_contact_conversation_close.md
  i18n/pt/docusaurus-plugin-content-docs/current/api/reference/contacts_api/post_contact_conversation_open.md
  i18n/pt/docusaurus-plugin-content-docs/current/api/reference/object_types/contact.md
  i18n/pt/docusaurus-plugin-content-docs/current/api/release_notes.md
  src/snippets/curl/contacts_api/_post_contact_conversation_close.mdx
  src/snippets/curl/contacts_api/_post_contact_conversation_open.mdx
  src/snippets/go/contacts_api/_post_contact_conversation_close.mdx
  src/snippets/go/contacts_api/_post_contact_conversation_open.mdx
  src/snippets/node/contacts_api/_post_contact_conversation_close.mdx
  src/snippets/node/contacts_api/_post_contact_conversation_open.mdx
  src/snippets/php/contacts_api/_post_contact_conversation_close.mdx
  src/snippets/php/contacts_api/_post_contact_conversation_open.mdx
  src/snippets/python/contacts_api/_post_contact_conversation_close.mdx
  src/snippets/python/contacts_api/_post_contact_conversation_open.mdx
  src/snippets/ruby/contacts_api/_post_contact_conversation_close.mdx
  src/snippets/ruby/contacts_api/_post_contact_conversation_open.mdx
Labels: documentation

#27 enh: code snippet example for custom fields update in contacts
  src/snippets/curl/contacts_api/_patch_contacts.mdx
  src/snippets/go/contacts_api/_patch_contacts.mdx
  src/snippets/node/contacts_api/_patch_contacts.mdx
  src/snippets/php/contacts_api/_patch_contacts.mdx
  src/snippets/python/contacts_api/_patch_contacts.mdx
  src/snippets/ruby/contacts_api/_patch_contacts.mdx
Labels: enhancement
