Repository callbellchat/callbell-public-docs, pull requests merged in 2024-11, with the labels that each got.

#48 enh: adds team_uuid as optional filter
  docs/api/reference/contacts_api/get_contacts.md
Labels: enhancement

#49 enh: location and contact card payloads for public api created message event
  docs/api/reference/object_types/message_contact_card.md
  docs/api/reference/object_types/message_location.md
  docs/api/reference/webhooks/message_events/message_created.md
  docs/api/release_notes.md
Labels: documentation

#50 enh: interactive messages public api events
  docs/api/reference/object_types/message_interactive_list.md
  docs/api/reference/object_types/message_reply_button.md
  docs/api/reference/webhooks/message_events/message_created.md
  docs/api/release_notes.md
Labels: documentation, ✅ Approved

#51 enh: message context, forward and reaction for webhook events
  docs/api/reference/object_types/message_context.md
  docs/api/reference/object_types/message_forward.md
  docs/api/reference/webhooks/message_events/message_created.md
  docs/api/release_notes.md
Labels: documentation

#55 feat: custom fields for livechat
  docs/livechat/_category_.json
  docs/livechat/tutorials/_category_.json
  docs/livechat/tutorials/custom_fields_creation/_category_.json
  docs/livechat/tutorials/custom_fields_creation/assets/custom_fields.png
  docs/livechat/tutorials/custom_fields_creation/assets/livechat_snippet.png
  docs/livechat/tutorials/custom_fields_creation/custom_fields_creation.md
  i18n/es/docusaurus-plugin-content-docs/current/livechat/tutorials/custom_fields_creation/assets/custom_fields.png
  i18n/es/docusaurus-plugin-content-docs/current/livechat/tutorials/custom_fields_creation/assets/livechat_snippet.png
  i18n/es/docusaurus-plugin-content-docs/current/livechat/tutorials/custom_fields_creation/custom_fields_creation.md
  i18n/fr/docusaurus-plugin-content-docs/current/livechat/tutorials/custom_fields_creation/assets/custom_fields.png
  i18n/fr/docusaurus-plugin-content-docs/current/livechat/tutorials/custom_fields_creation/assets/livechat_snippet.png
  i18n/fr/docusaurus-plugin-content-docs/current/livechat/tutorials/custom_fields_creation/custom_fields_creation.md
  i18n/it/docusaurus-plugin-content-docs/current/livechat/tutorials/custom_fields_creation/assets/custom_fields.png
  i18n/it/docusaurus-plugin-content-docs/current/livechat/tutorials/custom_fields_creation/assets/livechat_snippet.png
  i18n/it/docusaurus-plugin-content-docs/current/livechat/tutorials/custom_fields_creation/custom_fields_creation.md
  i18n/pt/docusaurus-plugin-content-docs/current/livechat/tutorials/custom_fields_creation/assets/custom_fields.png
  i18n/pt/docusaurus-plugin-content-docs/current/livechat/tutorials/custom_fields_creation/assets/livechat_snippet.png
  i18n/pt/docusaurus-plugin-content-docs/current/livechat/tutorials/custom_fields_creation/custom_fields_creation.md
Labels: documentation
